sudo: required
language: python

python:
  - "2.7"

install:
  - sudo pip install -r requirements.txt
  - sudo pip install coveralls

script:

  - sudo coverage run bobo.py -h
  - sudo coverage run bobo.py -v

after_success:
  - coveralls
